print("          )")
print("         ( ")
print("     ^    ) ")
print("    / \ --- ")
print("   /   \| | ")
print("  /     \ |  ")
print(" /       \| ")
print("/         \ ")
print("|  -    -  \ ")
print("| | |  | |  \ ")
print("| |_|  |_|   \ ")
print("|  _     _   | ")
print("|            | ")
print("| | |   | |  | ")
print("| | |   | |  |       # ")
print("| |@|   |_|  |      ### ")
print("| | |        |     ##### ")
print("\/\/\/\/\/\/\/\/\/\/\/\/ ")